### ISSUE TITLE
view resized dimension

### ISSUE THREAD

**Issue by mykeblack** [ChaosinaCan/ClassicImages#21]
When an image is resized in the browser (which happens quite often in responsive websites) I need to check what size the image has been resized down to as well as the original size. This tool does not tell you that. Could we please have that functionality?  There is a browser extension in Chrome: [here](https://chrome.google.com/webstore/detail/view-image-info-propertie/jldjjifbpipdmligefcogandjojpdagn?utm_source=chrome-app-launcher-info-dialog) 
that has this functionality, but I've just moved over to using opera (since chrome removed the abilty to go back a page by pressing backspace!)

cheers.

**Comment by ChaosinaCan** [comment]
That shouldn't be too hard. I'll look into it.

**Comment by ChaosinaCan** [comment]
That extension injects a script into every page all the time to figure out exactly what image you clicked on. (And for some reason it connects to Google Analytics in the background?) Since I'd like to avoid injecting a script until you've actually clicked on something, and because the extension API only gives me the URL of the image you clicked on, I'm just going to search the page for an image with a matching URL. It won't work all the time, but it should work most of the time.

**Comment by ChaosinaCan** [comment]
Added in 8b632ac148f3ce24117132f8ccf9109a6b6fb671
